### ISSUE TITLE
Agenda Search & Filter

### ISSUE THREAD

**Issue by Jpoliachik** [Droidcon-Boston/conference-app-ios#15]
provide users with a means to search and/or filter for specific topics, speakers, etc.

The search should work also offline
The search should be a full-text search on the agenda

https://github.com/Droidcon-Boston/conference-app-android/issues/116

**Comment by AniketSK** [comment]
Hello! I'd like to take this in iOS too.

**Comment by Jpoliachik** [comment]
![ios-filter-func](https://user-images.githubusercontent.com/5148640/54496510-9ca08200-48c6-11e9-98a4-39b522c7cd5b.gif)
